apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-adapter
spec:
  replicas: {{ .Values.discordAdapter.replicaCount }}
  selector:
    matchLabels:
      app: discord-adapter
  template:
    metadata:
      labels:
        app: discord-adapter
    spec:
      containers:
        - name: discord-adapter
          image: "{{ .Values.discordAdapter.image.repository }}:{{ .Values.discordAdapter.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: pipelinepulse-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: discord-adapter
spec:
  selector:
    app: discord-adapter
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
